### ISSUE TITLE
Version in pom.xml hasn't changed

### ISSUE THREAD

**Issue by AmitGee** [AcadiaSoft/simm-lib#12]
Hi
The version in the pom hasn't changed as part of this update, it's still 2.2.1 . Would you not expect to increment this to 2.3 ? 
thanks

**Comment by Alec-Stewart** [comment]
You're right. It should be updated. I will push a change to master and retag 2.3.0 to that commit.

**Comment by Alec-Stewart** [comment]
Fixed with ISSUE-12 commit.

**Comment by AmitGee** [comment]
Great thanks very much Alec!
