### ISSUE TITLE
Update ISDA SIMM 2.4

### ISSUE THREAD

**Issue by luphord** [AcadiaSoft/simm-lib#16]
I just noticed that a **new version 2.4** of the ISDA SIMM® Methodology has been published on 2021-09-09. Now I wonder if an update to `simm-lib` is planned?
 
> September 9, 2021
> 
> ISDA has published the ISDA SIMM® Methodology, version 2.4, with an effective date of December 4, 2021.
> 
> The effective date of December 4, 2021 means that SIMM users should use SIMM version 2.4 to calculate the initial margin for their portfolios for close of business on Friday, December 3, 2021 onwards. This means that the first day for the exchange of initial margin calculated using SIMM 2.4 would be on Monday, December 6, 2021.
> 
> This version of SIMM includes updates based on the full recalibration and industry backtesting of the methodology.

From https://www.isda.org/2021/09/09/isda-publishes-isda-simm-v2-4/

**Comment by Alec-Stewart** [comment]
And update to this library for SUMM version 2.4 should be released today!

**Comment by luphord** [comment]
Awesome, thanks @Alec-Stewart !
I suggest to leave this issue open until the release, so that other users are more likely to notice.

**Comment by AmitGee** [comment]
Great news! Can you please also confirm that the library will continue supporting 1-day SIMM ?

**Comment by Alec-Stewart** [comment]
@AmitGee I can confirm that the library does continue to to support 1-day SIMM.

As for the delay, I can only apologize. Shortly after I replied to this, ISDA released some updated unit tests to us and we have been making changes to support them.

**Comment by ralfspoerer** [comment]
Thanks for the update @Alec-Stewart.
Can you already tell us a new date for the release of simm-lib 2.4?

**Comment by Alec-Stewart** [comment]
@ralfspoerer @AmitGee @luphord 

SIMM 2.4 update of the simm-lib has now been released.
