### ISSUE TITLE
SEC Jurisdiction ISDA tests not implemented

### ISSUE THREAD

**Issue by AmitGee** [AcadiaSoft/simm-lib#18]
It looks like the test suite is missing JS1 and JS2 tests - these appear to use a new 'CalculationMode' column in the ISDA unit test spec, that has values [Segregated, Unsegregated, Total]

**Comment by AmitGee** [comment]
I've created a PR for this :    #20

**Comment by joe-peterson-acadiasoft** [comment]
These tests are all included with the 2.5 version
